services:
  postgres:
    image: postgres:18.1-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./out/pgdata:/var/lib/postgresql
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"

  postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ./migrations:/migrations
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app-service
    env_file:
      - .env
    environment:
      SERVER_HOST: "0.0.0.0"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped